{{ if .Values.services.filestore.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-release-server
  labels:
    app: {{ .Release.Name }}-release-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-release-server
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-release-server
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config-maps/release-server-configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secrets/filestore-secret.yaml") . | sha256sum }}
    spec:
      containers:
        - name: release-server
          image: "{{ .Values.services.releaseServer.image.repository }}:{{ .Values.services.releaseServer.image.tag }}"
          imagePullPolicy: {{ .Values.services.releaseServer.image.pullPolicy }}
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-release-server-config
            - secretRef:
                name: {{ .Release.Name }}-filestore-secret
          readinessProbe:
            httpGet:
               path: /healthz
               port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
      restartPolicy: Always
      imagePullSecrets:
        - name: {{ .Release.Name }}-docker-secret
{{ end }}